name: Retrieve AWS Secret and Variable

on:
  push:
    branches:
      - main
      - master
      - feature/*
      - develop
  workflow_dispatch:

jobs:
  retrieve_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Firstly, insert your secrets in AWS Secret Manager
      # Then, you can retrieve the secrets based on your secret-id
      # If you have multiple secret key and value pairs like mine, you can parse
      # the entire json object and print the values you'd like to display/use

      - name: Get Secret Object
        run: |
          secret_object=$(aws secretsmanager get-secret-value --secret-id lovell-3.13-secrets --query SecretString --output json)

          # Parse specific keys from the secret object
          color=$(echo "$secret_object" | jq -r '. | fromjson | .color')
          weather=$(echo "$secret_object" | jq -r '. | fromjson | .weather')
          fruit=$(echo "$secret_object" | jq -r '. | fromjson | .fruit')

          echo "Secret value color is: $color"
          echo "Secret value weather is: $weather"
          echo "Secret value fruit is: $fruit"

  retrieve_parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Firstly, insert your parameter in AWS Systems Manager > Parameter Store
      # Then, you can retrieve the parameters using aws ssm get-parameter command

      - name: Get parameter object
        run: |
          plant=$(aws ssm get-parameter --name lovell-3.13-parameter --query Parameter.Value --output text)
          echo "Lovell's favourite flower is: $plant" 